version: '3.1'

services:
  postgres:
    image: postgres
    container_name: pg
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - docker_postgres:/var/lib/postgres
volumes:
  docker_postgres:

